---
- name: My first play
  hosts: all
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:

  - name: apt-get update
    become: yes
    apt:
      update_cache: yes
      force_apt_get: yes

  - name: "install nginx"
    become: yes
    become_method: sudo
    apt:
      name: nginx
      state: latest

  - name: start nginx
    become: yes
    service:
        name: nginx
        state: started

  - name: Copy website files to the server's document root
    become: yes
    copy:
      src: /Users/aybouras/Desktop/ansible-book/provisioning/index.html
      dest: /var/www/html
      mode: preserve

  - name: copy the nginx config file and restart nginx
    become: yes
    become_method: sudo
    template:
      src: /Users/aybouras/Desktop/ansible-book/provisioning/default
      dest: /etc/nginx/sites-available/default
    notify: Restart Nginx



  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted